language: rust
rust:
   - stable
   - beta
   - nightly
script:
   - cargo build --verbose
   - pip install --user --requirement requirements.txt
   - python build.py > newlib.rs
   - diff -u src/lib.rs newlib.rs
